apiVersion: v1
kind: ConfigMap
metadata:
  name: servicediscovery-config
data:
  appsettings.json: |
    {
      "AllowedHosts": "*",
      "ConnectionString": "",
      "AuthServiceAddress": ""
    }
  AuthServiceAddress: "https://auth.hemant.cloud"
  
