apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: servicediscovery-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
    - host: service.hemant.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: servicediscovery-service
                port:
                  number: 80
  tls:
    - hosts:
        - service.hemant.cloud
      secretName: servicediscovery-tls
