apiVersion: v1
kind: Secret
metadata:
  name: servicediscovery-secrets
type: Opaque
stringData:
  ConnectionString: "Data Source=/data/Database.db"
  AuthServiceClientId: "ServiceDiscovery"
  AuthServiceClientSecret: "abc.123"
