apiVersion: v1
kind: Service
metadata:
  name: servicediscovery-service
spec:
  selector:
    app: servicediscovery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
