apiVersion: v1
kind: Service
metadata:
  name: servicediscovery-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: rg-cancen-devops-workshop 
    service.beta.kubernetes.io/azure-pip-name: service-discovery-pip
spec:
  selector:
    app: servicediscovery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

