helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.18.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml

namespace: cert-manager
