helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.13.0
    releaseName: ingress-nginx
    namespace: ingress-nginx
    valuesFile: values.yaml

namespace: ingress-nginx
