apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  namespace: tripspark
  labels:
    app: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: myregistry.azurecr.io/my-dotnet-app:latest
          ports:
            - containerPort: 80
          env:
            - name: AZURE_SQL_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-sql-secret
                  key: AZURE_SQL_CONNECTION_STRING
